Sprint_4
Canonner/qa_python pull request #2
Opened 2023-09-18 12:29 UTC by Canonner

Добавлены юнит тесты в tests.py, добавлена фикстура в conftest.py, добавлено описание в README.md

2023-09-18 20:08 UTC, kadirovgm requested changes

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +    books_to_add = [
нужно исправить: мы должны придерживаться принципа атомарности тестов: один тест=одна проверка
В данном случае ты сразу проверяешь случай, когдадобавляют два одинаковых книги (должна добавляться лишь одна), просто добавление книги, добавление невалидной книги и добавление книги с более чем 40 символов - все эти тесты стоит написать отдельными

параметризация - это когда на вход одного и того же теста передаются разные значения из разных классов эквивалентности, при этом мы должны ожидать один и тот же результат на выходе

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +        assert collector.get_books_genre() == {
можно лучше: легче воспользовать конструкцией book in collector.get_books_genre()

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +    def test_add_new_book_seven_books_four_added(self, name):
можно лучше: для юнит теста чаще всего хватает одной положительной проверки для того, чтобы убедиться , что он отрабатывает правильно, для корнер кейсов нужно писать отдельные тесты

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +    def test_set_book_genre_eight_books_received_five_genres(self, name, genre):
нужно исправить: для проверки метода set_book_genre можно воспользоваться меньшим количеством проверок

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +    books_with_genre = [
нужно исправить: достаточно одной положительной проверки

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +    def test_get_books_with_specific_genre_valid_genre_book_received(self, books_collector):
вот так более верно!

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +            'Смерть на ЗиЛе',
достаточно проверять на меьншем количестве тестовых данных для облегчения чтения кода

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +        # Проверяем, что новую книгу нельзя добавить в Избранное, если ее нет в списке книг
нужно исправить: это скорее отдельный тест

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +    def test_delete_book_from_favorites_one_book_deleted_empty_list(self, books_collector):
хороший тест!

2023-09-18 20:08 UTC, kadirovgm commented on tests.py
> +    def test_get_list_of_favorites_books_one_book_received_list_with_one_book(self, books_collector):
тоже хороший тест!

2023-09-19 06:08 UTC, Canonner commented on tests.py
> +        # Проверяем, что новую книгу нельзя добавить в Избранное, если ее нет в списке книг
Правильно ли я понимаю, что надо вынести в отдельный тест проверку добавления в Избранное книги, которая отсутствует в словаре книг?

2023-09-19 06:10 UTC, Canonner commented on tests.py
> +    def test_delete_book_from_favorites_one_book_deleted_empty_list(self, books_collector):
Правильно ли я понимаю, что тест  для метода delete_book_from_favorites переделывать не надо? Меня смущает пример с кодом на красном фоне. 
![image](https://github.com/Canonner/Sprint_4/assets/139960782/928682bd-87d0-4f8e-9524-b2726e6ea003)

2023-09-19 06:21 UTC, Canonner commented on tests.py
> +            'Смерть на ЗиЛе',
Правильно ли я понимаю, что Тест для метода get_books_for_children можно провести на двух книгах - одна из которых детская, а вторая не детская? Или может, на трех - одна детская, две не детские?
Сейчас у меня список книг формируется универсальной фикстурой, одной на многие методы.
Возможно я не прав, но по моей задумке, если один раз прочитать код фикстуры, то будет понятно, какой принцип тестовых данных используется во всех методах с фикстурой. И код самого теста умещается в две строки, плюс три строки ожидаемого результата.
Если переделать, то код в этом методе увеличится на 4 строки, если использовать две книги, и на 6 строк в случае с тремя книгами, а ожидаемый результат уменьшится на две строки.

2023-09-19 06:29 UTC, Canonner commented on tests.py
> +    books_with_genre = [
Исправлено, удалена параметризация, оставлена только фикстура. На вход теста подается одна книга, а ОР - ее жанр.

2023-09-19 06:47 UTC, Canonner commented on tests.py
> +    books_to_add = [
К сожалению, в задании на проект противоречиво и неоднозначно сказано, что надо "полностью покрыть класс тестами" и в то же время "покрывать все сценарии не нужно: напиши 9-10 тестов". 
Но для того, чтобы покрыть тестами весь класс, используя принцип атомарности, надо написать примерно 15-20 тестов - например, только для теста метода add_new_book понадобится 4-5 тестов, отличающихся только ожидаемыми результатами. 
Будет ли считаться верным, если напишу не 9-10, а 15-20 тестов?
Стоит ли обратить внимание авторов курса на двусмысленность формулировки в задании?

![image](https://github.com/Canonner/Sprint_4/assets/139960782/bd256a94-3b1c-49c6-b57d-65a7676b0fe3)

2023-09-19 06:51 UTC, Canonner commented on .gitignore
> +
Я воспользовался уроком "Игнорирование" Спринт 4/4 → Тема 2/8: Git → Урок 5/19, разделом "Лайфхак: один .gitignore на все случаи жизни"
Удивлен, что лайфхак не помог, и что лучше без него.

2023-09-19 07:15 UTC, Canonner commented on .idea/.gitignore
Правильно ли я понимаю, что в этом замечании речь идет не про файл, а про папку .idea?

2023-09-19 07:42 UTC, kadirovgm commented on .idea/.gitignore
> Правильно ли я понимаю, что в этом замечании речь идет не про файл, а про папку .idea?

да, извини, про папку .idea

2023-09-19 07:45 UTC, kadirovgm commented on tests.py
> +    books_to_add = [
Привет! придерживаться атомарности точно нужно, если напишешь 15 тестов будет хорошо, но я буду оценивать так, чтобы не было излишних тестов. Нужно выдерживать баланс и придерживаться техник тест дизайна для оптимизации количества тестов.

В задании сказано 9-10 тестов, что означает не нужно упарываться и глубоко покрывать все сценарии, достаточно выявить самые основные кейсы и покрыть их.

про возникшую противоречивость я подсвечу авторам курса, спасибо за фидбек!

2023-09-19 07:49 UTC, kadirovgm commented on tests.py
> +            'Смерть на ЗиЛе',
Да, можно ограничиться двумя книгами (детская/не детская), универсальная фикстура не всегда есть хорошо, потому что она часто создает сложности для чтения кода и усложняет тесты. 
В данных тестах было бы достаточно для каждого теста отдельно добавлять книгу, ровно столько, сколько нужно для теста. Таким образом мы не будем занимать лишнюю память программы и повысим простоту тестов, что трактуется принципами python

2023-09-19 07:49 UTC, kadirovgm commented on tests.py
> +        # Проверяем, что новую книгу нельзя добавить в Избранное, если ее нет в списке книг
правильно

2023-09-19 07:51 UTC, kadirovgm commented on tests.py
> +    def test_delete_book_from_favorites_one_book_deleted_empty_list(self, books_collector):
Переделывать не нужно, по своей сути он верный. Не совсем понял что смущает в коде "на красном фоне", гитхаб так подсвечивает тебе удаленный тобой код, или я тебя не понял все таки?

2023-09-19 08:24 UTC, Canonner commented on tests.py
> +            'Смерть на ЗиЛе',
Спасибо за ответ! Т.е. под чтением кода имеется в виду чтение кода программой.
Стало намного понятнее, как писать код и использовать тестовые данные.

2023-09-19 08:24 UTC, Canonner commented on tests.py
> +    def test_delete_book_from_favorites_one_book_deleted_empty_list(self, books_collector):
Про удаленный мной код понял, я просто первый раз в жизни получаю комменты в гитхаб и не знал этого. Мне показалось, что это ты мне прислал пример, как надо сделать))

Огромное спасибо за быстрые комментарии, буду исправлять! 
Сергей Царев уже сказал мне, что в следующий раз надо писать напрямую ему, чтобы не отвлекать ревьюверов лишний раз.

2023-09-20 19:57 UTC, kadirovgm commented on tests.py
> +    def test_delete_book_from_favorites_one_book_deleted_empty_list(self, books_collector):
не за что!

2023-09-20 20:04 UTC, kadirovgm approved these changes

2023-09-20 20:04 UTC, kadirovgm commented on tests.py
> +    book_to_add = [
можно лучше: слишком много тестовых данных, достаточно проверить на граничных значениях, например, 1 и 40 - что книги со столькими символами добавляются, другие проверки излишны

2023-09-20 20:04 UTC, kadirovgm commented on tests.py
> +    def test_add_new_books_two_same_books_one_added(self):
отлично!

2023-09-20 20:04 UTC, kadirovgm commented on tests.py
> +        'Самоучитель по игре на воображаемом контрабасе'
можно лучше! вот тут супер, только 46 уже тоже скорее лишняя))

2023-09-20 20:04 UTC, kadirovgm commented on tests.py
> +    def test_get_book_genre_one_book_received_genre(self):
супер!

2023-09-21 11:04 UTC, merged